spring:
  application:
    name: store
    version: 1.0.0
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
server:
  servlet:
    context-path: /api/v1/